"""
    stochastic_lopf.jl

Scenario-based stochastic Linear Optimal Power Flow.

Implements the Sample Average Approximation (SAA) approach:
  - S load/wind scenarios are generated by the LSTM forecaster
  - lopf_multiperiod is solved independently for each scenario
  - Results are aggregated: E[cost], CVaR_90, best/worst case, mean LMP

This provides a distribution of operational costs under demand uncertainty,
compared to the deterministic baseline that uses a single point forecast.

Usage:
  scenarios = predict_scenarios(fc, history; n_scenarios=7)
  result    = lopf_stochastic(net, scenarios.scenarios; T=24)
  println("E[cost] = ", result.expected_cost)
  println("CVaR90  = ", result.cvar_90)
"""

@isdefined(Network) || include(joinpath(@__DIR__, "network.jl"))
@isdefined(lopf_multiperiod) || include(joinpath(@__DIR__, "dispatch.jl"))

using Statistics
using Printf

# ─────────────────────────────────────────────────────────────────────────────
#  Main stochastic solver
# ─────────────────────────────────────────────────────────────────────────────

"""
    lopf_stochastic(net, load_scenarios; wind_scenarios, T, weights, verbose)
                                                         → NamedTuple

Solve multi-period LOPF over `S` load scenarios using Sample Average Approximation.

Arguments:
  net             :: Network          — power network
  load_scenarios  :: Matrix{Float64}  — T × S matrix; column s = load profile for scenario s
                                        (values in [0, 1] pu relative to nominal load)

Keyword arguments:
  wind_scenarios  :: Matrix{Float64}  — T × S wind profile matrix (default: repeat DEFAULT_WIND_PROFILE)
  T               :: Int              — time horizon (default: size(load_scenarios, 1))
  weights         :: Vector{Float64}  — scenario probabilities (default: uniform 1/S)
  verbose         :: Bool             — print per-scenario progress (default: false)

Returns a NamedTuple with:
  expected_cost :: Float64            — E[cost] = weighted mean over scenarios
  cvar_90       :: Float64            — CVaR at 90% level (expected cost in worst 10% scenarios)
  worst_cost    :: Float64            — maximum scenario cost
  best_cost     :: Float64            — minimum scenario cost
  std_cost      :: Float64            — standard deviation of scenario costs
  costs         :: Vector{Float64}    — per-scenario total cost (length S)
  mean_lmp      :: Dict{String,Float64} — time-average LMP per bus (averaged across scenarios)
  n_feasible    :: Int                — number of feasible scenarios (status == "OPTIMAL")
  status        :: String             — "OK" if all scenarios feasible, else "PARTIAL"

Interpretation:
  - expected_cost vs. deterministic_cost shows the value of stochastic scheduling
  - CVaR_90 quantifies the tail risk of high-cost outcomes
  - std_cost measures sensitivity to forecast uncertainty
"""
function lopf_stochastic(net::Network,
                         load_scenarios::Matrix{Float64};
                         wind_scenarios :: Matrix{Float64} = Matrix{Float64}(undef, 0, 0),
                         T              :: Int     = size(load_scenarios, 1),
                         weights        :: Vector{Float64} = Float64[],
                         verbose        :: Bool    = false)

    T_scen, S = size(load_scenarios)
    T = min(T, T_scen)

    # Default wind: repeat DEFAULT_WIND_PROFILE across all scenarios
    if isempty(wind_scenarios)
        base_wind = DEFAULT_WIND_PROFILE
        wwind = T <= 24 ? base_wind[1:T] :
                          [base_wind[((t-1) % 24) + 1] for t in 1:T]
        wind_scenarios = repeat(wwind, 1, S)
    end

    # Scenario weights
    w = isempty(weights) ? fill(1.0 / S, S) : weights
    abs(sum(w) - 1.0) > 1e-6 && (w = w ./ sum(w))

    # ── Run one LOPF per scenario ─────────────────────────────────────────────
    costs      = Vector{Float64}(undef, S)
    all_lmps   = Vector{Dict{String,Vector{Float64}}}(undef, S)
    n_feasible = 0

    for s in 1:S
        load_prof = load_scenarios[1:T, s]
        wind_prof = wind_scenarios[1:T, s]

        r = lopf_multiperiod(net;
                T          = T,
                load_profile  = load_prof,
                wind_profile  = wind_prof,
                verbose    = false)

        if string(r.status) == "OPTIMAL"
            costs[s]    = r.total_cost
            all_lmps[s] = r.lmp       # field name from lopf_multiperiod return
            n_feasible += 1
        else
            # Infeasible scenario: penalise with large cost
            costs[s]    = 1e9
            all_lmps[s] = Dict{String,Vector{Float64}}()
            verbose && @printf("[Stochastic LOPF] scenario %d/%d INFEASIBLE\n", s, S)
        end

        verbose && @printf("[Stochastic LOPF] scenario %2d/%d  cost=%.1f €\n",
                           s, S, costs[s])
    end

    # ── Aggregate statistics ──────────────────────────────────────────────────
    expected_cost = sum(w .* costs)
    std_cost      = sqrt(sum(w .* (costs .- expected_cost).^2))

    # CVaR at 90%: expected cost in the worst 10% of scenarios
    sorted_costs = sort(costs, rev=true)
    n_tail       = max(1, ceil(Int, 0.10 * S))
    cvar_90      = mean(sorted_costs[1:n_tail])

    # Mean LMP across feasible scenarios (time-average per bus)
    mean_lmp = Dict{String,Float64}()
    if n_feasible > 0
        feasible_lmps = filter(!isempty, all_lmps)
        bus_names_set = keys(first(feasible_lmps))
        for bus in bus_names_set
            lmp_vals = Float64[]
            for lmp_t in feasible_lmps
                haskey(lmp_t, bus) && append!(lmp_vals, lmp_t[bus])
            end
            mean_lmp[bus] = isempty(lmp_vals) ? 0.0 : mean(lmp_vals)
        end
    end

    status = n_feasible == S ? "OK" : "PARTIAL ($(n_feasible)/$(S) feasible)"

    return (
        expected_cost = expected_cost,
        cvar_90       = cvar_90,
        worst_cost    = maximum(costs),
        best_cost     = minimum(costs),
        std_cost      = std_cost,
        costs         = costs,
        mean_lmp      = mean_lmp,
        n_feasible    = n_feasible,
        status        = status,
    )
end

# ─────────────────────────────────────────────────────────────────────────────
#  Comparison utility
# ─────────────────────────────────────────────────────────────────────────────

"""
    compare_deterministic_stochastic(det_result, stoch_result) → Nothing

Prints a formatted comparison table between deterministic LOPF and stochastic LOPF.
Useful for thesis results section.
"""
function compare_deterministic_stochastic(det_result, stoch_result)
    println("\n" * "─"^62)
    println("  Deterministic LOPF  vs  Stochastic LOPF (SAA)")
    println("─"^62)
    @printf("  %-30s  %12s  %12s\n", "Metric", "Deterministic", "Stochastic")
    println("  " * "─"^58)

    det_cost = det_result.total_cost
    @printf("  %-30s  %12.2f  %12.2f  €\n",
            "Expected cost", det_cost, stoch_result.expected_cost)
    @printf("  %-30s  %12s  %12.2f  €\n",
            "CVaR 90%", "—", stoch_result.cvar_90)
    @printf("  %-30s  %12s  %12.2f  €\n",
            "Worst-case cost", "—", stoch_result.worst_cost)
    @printf("  %-30s  %12s  %12.2f  €\n",
            "Best-case cost", "—", stoch_result.best_cost)
    @printf("  %-30s  %12s  %12.2f  €\n",
            "Cost std dev", "—", stoch_result.std_cost)

    Δ = stoch_result.expected_cost - det_cost
    Δ_pct = 100 * Δ / max(abs(det_cost), 1.0)
    println("  " * "─"^58)
    @printf("  %-30s  %12.2f  €  (%+.1f%%)\n",
            "E[cost] difference", Δ, Δ_pct)
    @printf("  %-30s  %12d\n",
            "Feasible scenarios", stoch_result.n_feasible)
    println("─"^62)
end
